const dinners = [
	"Tacos",
	"Fajitas",
	"Chicken in Gravy",
	"Fried Shrimp",
	"Shrimp Pasta",
	"Salmon",
	"Trout",
	"Flounder",
	"Crab Cakes",
	"Enchiladas",
	"Chicken Parm",
	"Chicken Cordon Bleu",
	"Chicken a la King",
	"Chicken Alfredo",
	"Chicken Patties",
	"Chicken Noodle Soup",
	"Roast Chicken",
	"Fried Chicken",
	"Chicken Pot Pie",
	"Steak",
	"Steak Kebabs",
	"Pork Roast",
	"Ham",
	"Pot Roast",
	"Pork Chops",
	"Stewed Chicken",
	"Roast Beef Sandwiches",
	"Chicken Cutlets",
	"Beef Soup",
	"Soup and Sandwiches",
	"Pasta Primavera",
	"Mushroom Pasta",
	"Baby Tomato Pasta",
	"Tortellini",
	"Fried Eggplant",
	"Eggplant Parm",
	"Homemade Pizza",
	"Spaghetti and Meatballs",
	"Ravioli",
	"Gnocchi",
	"Stir Fry",
	"Teriyaki Chicken",
	"Turkey Dinner",
	"Hot Turkey Sandwiches",
	"Chicken Sandwiches",
	"Cheeseburgers",
	"Ribs",
	"Hotdogs",
	"Grilled Chicken",
	"Barbecue Chicken",
	"Cheesesteaks",
	"Chili",
	"Chicken Marsala",
	"Carbonara",
];

const takeouts = [
	"Arby's",
	"Chick-fil-A",
	"Pizza",
	"Panera",
	"Smashburger",
	"Applebee's",
	"KFC",
	"Popeyes",
	"Hunan East",
	"Tokyo Mandarin",
	"Wawa",
];

export { dinners, takeouts };
